version: '3.8'

services:

  INSOF_PROJECT:
    build:
      context: .
      dockerfile: Dockerfile
    image: maven
    container_name: maven
    ports:
      - "7777:7777"

  database:
    image: postgres:latest
    container_name: bekhruz
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
  storage_data: {}
