version: '3.1'

services:

#  INSOF_PROJECT:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: maven
#    container_name: maven
#    ports:
#      - "7778:7778"

  database:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: insof_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bexa
